# -*- coding: utf-8 -*-
"""01.intro_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pf3WFn9hLatBHhbPAyzvQIsM9Qz6-Cvr
"""

x = 2
x

y = 100
y + 300



"""# Acesta este un markdown

Pentru a folosi comenzi de bash folosim "!"
"""

!python --version

pip list

import this

"""# Pentru a instala un alt modul in python, se foloseste pip"""

!pip install that

import that

